import SiteHeader from './components/SiteHeader';
import SurfaceExplorer from './components/SurfaceExplorer';
import ThemePreview from './components/ThemePreview';
const GITHUB = 'https://github.com/tofunori/atelier-studio';
const DOWNLOAD = `${GITHUB}/releases/latest`;
export default function Page() {
    return <>
 <a className="skip-link" href="#main">Skip to content</a><SiteHeader />
 <main id="main">
  <section className="hero container"><div className="hero-top"><p className="eyebrow">A native workspace for research</p><span className="release">macOS · Open source</span></div><h1>Your research,<br /><span>in one workspace.</span></h1><div className="hero-bottom"><p>Work with AI agents, read papers, edit manuscripts, and inspect figures—without losing project context.</p><a className="button-primary" href={DOWNLOAD}>Download for Mac <span aria-hidden="true">↗</span></a></div><figure className="hero-image"><img src="/media/workspace.png" width="1600" height="1000" alt="Atelier conversation and project navigator, showing a fictional research plan" fetchPriority="high"/><figcaption><span>Atelier Studio</span><span>Real interface. Fictional project.</span></figcaption></figure></section>
  <section id="workspace" className="container section"><div className="section-heading"><p className="eyebrow">01 / The workspace</p><h2>A place for every<br />part of the process.</h2><p>Move between the conversation and the work itself. Your code, documents, and figures remain within reach.</p></div><SurfaceExplorer /></section>
  <section className="container workflows" aria-label="Research workflows"><article><span className="index">01</span><h3>Think with an agent.</h3><p>Work with Claude Code or Codex in project conversations. Review activity, add context, and steer the next step.</p></article><article><span className="index">02</span><h3>Write beside your sources.</h3><p>Read PDFs, use your Zotero library, and work on Markdown or LaTeX without leaving the project.</p></article><article><span className="index">03</span><h3>Look closely at the result.</h3><p>Browse figures, annotate an area that needs attention, and bring that feedback into the conversation.</p></article></section>
  <section className="tour-section"><div className="container"><div className="section-heading compact"><p className="eyebrow">A closer look</p><h2>Follow the work.</h2><p>A short visit through the gallery, figure annotation, and LaTeX reading, with the conversation always within reach.</p></div><video controls playsInline preload="none" poster="/media/workspace.png" width="1600" height="1000" aria-label="Silent tour of Atelier panels, figure annotation, and LaTeX reading using fictional demonstration content"><source src="/media/atelier-tour.mp4" type="video/mp4"/><a href="/media/atelier-tour.mp4">Download the workspace tour</a></video><p className="media-note">Silent demonstration · All documents, conversations, and data are fictional.</p></div></section>
  <section id="appearance" className="container section"><div className="section-heading"><p className="eyebrow">02 / Make room to focus</p><h2>Quiet by design.<br />Personal by choice.</h2><p>Restrained controls, lighter typography, and a choice of themes. Preview Graphite, Pierre, or the familiar colours of Monokai.</p></div><ThemePreview /></section>
  <section id="download" className="container download section"><div><p className="eyebrow">03 / Get started</p><h2>Your next project<br />starts here.</h2><a className="button-primary" href={DOWNLOAD}>Download Atelier <span aria-hidden="true">↗</span></a><p className="download-meta">macOS · Apple Silicon · Free and open source</p></div><div className="installation"><h3>A few things to know.</h3><p>Download the DMG from GitHub Releases and move Atelier to Applications. Connect a supported agent to start a conversation.</p><p>Agent access requires your own provider account or API credentials. LaTeX compilation needs a local TeX installation; PDF text extraction uses Poppler.</p><p>Current builds are not notarized by Apple. Follow the installation instructions if macOS blocks the first launch.</p><a className="text-link" href={`${GITHUB}#installation`}>Installation instructions ↗</a><a className="text-link" href={`${GITHUB}/releases`}>Release notes ↗</a></div></section>
 </main><footer className="container"><span>Atelier Studio</span><p>A workspace for the work behind the research.</p><a href={`${GITHUB}/blob/main/LICENSE`}>MIT license ↗</a></footer>
 </>;
}
