import { assetPath } from './site';
import SiteHeader from './components/SiteHeader';
import SurfaceExplorer from './components/SurfaceExplorer';
import ThemePreview from './components/ThemePreview';
const GITHUB = 'https://github.com/tofunori/atelier-studio';
const DOWNLOAD = `${GITHUB}/releases/latest`;
export default function Page() {
    return <>
 <a className="skip-link" href="#main">Skip to content</a><SiteHeader />
 <main id="main">
  <section className="hero container"><div className="hero-top"><p className="eyebrow">Scientific research · Master’s &amp; PhD</p><span className="release">macOS · Open source</span></div><h1>Your thesis,<br /><span>in one workspace.</span></h1><div className="hero-bottom"><p>A native macOS workspace for master’s students, PhD candidates, and researchers. Bring your literature, analysis, figures, and thesis chapters together, with AI assistance in context.</p><a className="button-primary" href={DOWNLOAD}>Download for Mac <span aria-hidden="true">↗</span></a></div><figure className="hero-image"><img src={assetPath("/media/workspace.png")} width="1600" height="1000" alt="Atelier conversation and project navigator, showing a fictional research plan" fetchPriority="high"/><figcaption><span>Atelier Studio</span><span>Real interface. Fictional project.</span></figcaption></figure></section>
  <section id="workspace" className="container section"><div className="section-heading"><p className="eyebrow">01 / The workspace</p><h2>From research question<br />to manuscript.</h2><p>Read a paper beside your notes. Inspect a figure beside the analysis. Review rendered LaTeX beside the conversation. Keep each part of your research within reach.</p></div><SurfaceExplorer /></section>
  <section className="container workflows" aria-label="Research workflows"><article><span className="index">01</span><h3>Read the literature.</h3><p>Read papers in the PDF viewer and work with your Zotero library. Bring selected context into conversations as you develop your research question.</p></article><article><span className="index">02</span><h3>Develop the analysis.</h3><p>Work on scripts, use the terminal, and inspect outputs in the figure gallery. Mark a region and draft precise feedback for the next revision.</p></article><article><span className="index">03</span><h3>Write and revise.</h3><p>Edit thesis chapters and scientific manuscripts in LaTeX or Markdown. Read rendered prose and equations, and work through revisions with Claude Code or Codex.</p></article></section>
  <section className="tour-section"><div className="container"><div className="section-heading compact"><p className="eyebrow">A closer look</p><h2>See the research workflow.</h2><p>Move from analysis scripts to figures, annotate a detail, then read the methods and equations in LaTeX. The conversation stays alongside the work.</p></div><video controls playsInline preload="none" poster={assetPath("/media/workspace.png")} width="1600" height="1000" aria-label="Silent tour of Atelier panels, figure annotation, and LaTeX reading using fictional demonstration content"><source src={assetPath("/media/atelier-tour.mp4")} type="video/mp4"/><a href={assetPath("/media/atelier-tour.mp4")}>Download the workspace tour</a></video><p className="media-note">Silent demonstration · All documents, conversations, and data are fictional.</p></div></section>
  <section id="appearance" className="container section"><div className="section-heading"><p className="eyebrow">02 / Make room to focus</p><h2>Quiet by design.<br />Personal by choice.</h2><p>Restrained controls, lighter typography, and a choice of themes. Preview Graphite, Pierre, or the familiar colours of Monokai.</p></div><ThemePreview /></section>
  <section id="download" className="container download section"><div><p className="eyebrow">03 / Get started</p><h2>Make room for<br />your research.</h2><a className="button-primary" href={DOWNLOAD}>Download Atelier <span aria-hidden="true">↗</span></a><p className="download-meta">macOS · Apple Silicon · Free and open source</p></div><div className="installation"><h3>A few things to know.</h3><p>Download the DMG from GitHub Releases and move Atelier to Applications. Connect a supported agent to start a conversation.</p><p>Agent access requires your own provider account or API credentials. LaTeX compilation needs a local TeX installation; PDF text extraction uses Poppler.</p><p>Current builds are not notarized by Apple. Follow the installation instructions if macOS blocks the first launch.</p><a className="text-link" href={`${GITHUB}#installation`}>Installation instructions ↗</a><a className="text-link" href={`${GITHUB}/releases`}>Release notes ↗</a></div></section>
 </main><footer className="container"><span>Atelier Studio</span><p>For the work behind a thesis, a paper, a discovery.</p><a href={`${GITHUB}/blob/main/LICENSE`}>MIT license ↗</a></footer>
 </>;
}
