import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { ChatNotice } from './ChatNotice';
afterEach(()=>{cleanup();vi.useRealTimers();});
const notice={text:'effet fournisseur incertain après redémarrage',requestType:'sendReceipt',clientMessageId:'a',actionLabel:'Vérifier l’état',onAction:vi.fn()};
it('opens on demand, verifies without resending, and closing retains the icon',async()=>{
 const {rerender}=render(<ChatNotice notice={notice}/>);
 expect(screen.queryByText('Envoi à vérifier')).toBeNull();
 fireEvent.click(screen.getByRole('button',{name:'Afficher l’alerte du chat'}));
 await screen.findByText('Envoi à vérifier');
 fireEvent.click(screen.getByRole('button',{name:'Vérifier l’état'}));
 expect(notice.onAction).toHaveBeenCalledOnce();
 expect(screen.getByText('Vérification en cours')).toBeTruthy();
 rerender(<ChatNotice notice={{...notice}}/>);
 expect(screen.getByText('État toujours incertain')).toBeTruthy();
 fireEvent.click(screen.getByRole('button',{name:'Fermer le détail de l’alerte'}));
 expect(screen.getByRole('button',{name:'Afficher l’alerte du chat'})).toBeTruthy();
});
it('ends a verification that receives no reply and lets the user retry',async()=>{
 const {rerender}=render(<ChatNotice notice={notice}/>);
 fireEvent.click(screen.getByRole('button',{name:'Afficher l’alerte du chat'}));
 await screen.findByText('Envoi à vérifier');
 vi.useFakeTimers();
 fireEvent.click(screen.getByRole('button',{name:'Vérifier l’état'}));
 act(()=>vi.advanceTimersByTime(8000));
 expect(screen.getByText('Vérification indisponible')).toBeTruthy();
 expect(screen.getByRole('button',{name:'Vérifier l’état'}).hasAttribute('disabled')).toBe(false);
 rerender(<ChatNotice notice={{...notice,text:'Échec confirmé : accès refusé'}}/>);
 expect(screen.getByText('Échec confirmé : accès refusé')).toBeTruthy();
 expect(screen.queryByText('Vérification indisponible')).toBeNull();
});
