/** Globals installed at runtime by page.evaluate / VM fixtures, never shipped to the app.
 * These deliberate test doubles accept incomplete and invalid values. Keep the dynamic
 * boundary here; production gallery APIs are checked by src/browser/globals.d.ts. */
export {};
type InjectedTestValue = any;
declare global {
  var LatexReading: InjectedTestValue;
  var PdfSync: InjectedTestValue;
  var __TAURI_EVENT_PLUGIN_INTERNALS__: InjectedTestValue;
  var __TAURI_INTERNALS__: InjectedTestValue;
  var __activeSnippetObserverTargets: Set<Element>;
  var __attachMessages: InjectedTestValue;
  var __bench: InjectedTestValue;
  var __benchHooked: boolean;
  var __benchNoMarginMeasure: InjectedTestValue;
  var __benchNullBubble: InjectedTestValue;
  var __benchObserver: MutationObserver;
  var __benchRaf: InjectedTestValue;
  var __benchStart: number;
  var __committedReload: InjectedTestValue;
  var __dv: InjectedTestValue;
  var __firstReload: InjectedTestValue;
  var __gutterDecision: InjectedTestValue;
  var __lastGoodPage: InjectedTestValue;
  var __msgs: InjectedTestValue;
  var __pdfStats: InjectedTestValue;
  var __releaseDestroy: InjectedTestValue;
  var __releaseDrain: () => void;
  var __reviewRowsBeforeSelection: InjectedTestValue;
  var __rewrapAll: () => number;
  var __scrollTrace: InjectedTestValue;
  var __setValueCalls: number;
  var __waitingForDestroy: boolean;
  var __waitingForDrain: boolean;
  var addHighlightFromReadingSel: InjectedTestValue;
  var alertOn: InjectedTestValue;
  var annotationFailure: InjectedTestValue;
  var annotationResult: InjectedTestValue;
  var blankFrames: number;
  var controller: InjectedTestValue;
  var copied: InjectedTestValue;
  var decodes: InjectedTestValue;
  var downloads: InjectedTestValue;
  var editor: InjectedTestValue;
  var expectedScroll: number;
  var finish: InjectedTestValue;
  var gate: InjectedTestValue;
  var isTauri: InjectedTestValue;
  var oldPage: InjectedTestValue;
  var oldTop: number;
  var postChatPayload: InjectedTestValue;
  var refresh: InjectedTestValue;
  var release: InjectedTestValue;
  var requests: InjectedTestValue;
  var resolveAlert: InjectedTestValue;
  var resume: InjectedTestValue;
  var revision: InjectedTestValue;
  var scrollCalls: (ScrollIntoViewOptions & {line?:string})[];
  var sent: InjectedTestValue;
  var sentToAtelier: InjectedTestValue;
  var streamChild: InjectedTestValue;
  var texcAll: InjectedTestValue;
  var texcMarks: InjectedTestValue;
  var texcOpen: InjectedTestValue;
  var texts: InjectedTestValue;
  var updateMessage: InjectedTestValue;
  var visiblePages: InjectedTestValue;
  var waiting: InjectedTestValue;
  var wrapSel: InjectedTestValue;
  var zoom: InjectedTestValue;
}
