import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
test('Atelier subagents keep one group, open reports and settle without duplicate chips',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const result=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {AgentActivityGroup,AgentDetailPanel} from './src/components/chat/AgentActivity';import {groupAgentRows} from './src/components/chat/groupAgentRows';import {setLanguage} from './src/lib/i18n';setLanguage('fr');
 const activity=(id,child,status,index)=>({type:'event',key:id,index,event:{kind:'tool_update',id,name:'agent:activity',status:'completed',output:'',ts:index,agentActivity:{tool:'activity',receiverThreadIds:[child],agentThreadId:child,agentPath:'/root/'+child,agentsStates:{[child]:{status}},prompt:'Comparer les publications et les bilans régionaux.'}}});
 function App(){const[done,setDone]=React.useState(false),[agent,open]=React.useState(null),[words,setWords]=React.useState("Les sources");window.streamChild=()=>setWords("Les sources ont été regroupées par année.");window.finish=()=>setDone(true);window.resume=()=>setDone(false);const rows=groupAgentRows([activity('a','feux_2002_2014','completed',1),activity('b','feux_2015_2023','running',2),{type:'event',key:'prose',index:3,event:{kind:'text',text:'Je vérifie les sources.'}},...(done?[activity('c','feux_2015_2023','completed',4)]:[])],[{key:'turn',startIndex:0,endIndex:10}]);const raw="const result = await tools.exec_command({cmd: 'cat Makefile'});";return <main><article><p>Je croise les études sur les glaciers et les bilans d’incendies.</p>{rows.map(r=>r.type==='agents'?<AgentActivityGroup key={r.key} actions={r.actions} onOpenAgent={open}/>:<p key={r.key}>{r.event.text}</p>)}<textarea placeholder="Écrire un message…"/></article>{agent&&<AgentDetailPanel agent={agent} onClose={()=>open(null)} events={[{kind:'streaming',text:words},{kind:'tool_update',id:'read',name:'functions.exec',detail:raw,input:{raw},status:'completed',output:'Notes de lecture'}]}/>}</main>}createRoot(document.getElementById('root')).render(<App/>);`,resolveDir:root,loader:'tsx'},alias:{'@':path.join(root,'src')},bundle:true,write:false,outdir:'/tmp/subagent-ui-test',define:{'import.meta.glob':'__emptyGlob'},banner:{js:'const __emptyGlob=()=>({});'},loader:{'.woff':'dataurl','.woff2':'dataurl','.ttf':'dataurl'},jsx:'automatic',platform:'browser',format:'iife'});
 await page.setContent('<div id="root"></div>');
 for(const file of result.outputFiles)if(file.path.endsWith('.css'))await page.addStyleTag({content:file.text});else await page.addScriptTag({content:file.text});
 const app=await readFile(path.join(root,'src/App.css'),'utf8');
 const tokens=await readFile(path.join(root,'src/styles/tokens.css'),'utf8');
 const primitives=await readFile(path.join(root,'src/styles/primitives.css'),'utf8');
 await page.addStyleTag({content:app.replace(/@import[^;]+;/g,'')+tokens+primitives+'\nbody{margin:0;background:var(--bg);color:var(--fg);font:13px -apple-system,sans-serif}main{display:flex;min-height:650px;padding:30px}article{flex:1;min-width:0;max-width:700px;margin:30px auto;padding:0 20px}p{line-height:1.7;margin-bottom:28px}textarea{margin-top:70px;width:100%;background:var(--bg-card);border:1px solid var(--border);border-radius:14px;padding:15px}button{font:inherit}'});
 const group=page.getByTestId('subagent-activity-inline-group');
 await expect(group).toHaveCount(1);
 await expect(page.locator('.agent-row')).toHaveCount(2);
 await expect(page.locator('.agent-chip')).toHaveCount(0);
 await page.getByRole('button',{name:'Ouvrir le sous-agent Feux 2015 2023'}).click();
 await expect(page.getByTestId('agent-transcript')).toContainText('Les sources');
 await expect(page.locator('.agent-report')).toContainText('Les sources');
 await expect(page.locator('.agent-detail-prompt')).not.toBeVisible();
 await page.locator('.agent-detail-disclosure > summary').first().click();
 await expect(page.locator('.agent-detail-prompt')).toBeVisible();
 await page.locator('.agent-detail-activity > summary').click();
 await expect(page.locator('.agent-tool-line-text')).toContainText('Lit Makefile');
 await page.locator('.agent-tool-result > summary').click();
 await expect(page.locator('.agent-tool-output')).toBeVisible();
 await page.evaluate(()=>window.streamChild());
 await expect(page.locator('.agent-report')).toContainText('regroupées par année');
 await expect(page.locator('.agent-tool-output')).toBeVisible();
 await page.locator('.agent-detail-activity > summary').focus();
 expect(await page.locator('.agent-detail-activity > summary').evaluate(el=>getComputedStyle(el).outlineStyle)).toBe('none');
 await page.screenshot({path:'/tmp/atelier-subagent-detail-ui.png'});
 await page.getByRole('button',{name:'Fermer',exact:true}).click();
 await page.evaluate(()=>window.finish());
 await expect(group).toHaveCount(1);
 await expect(group.getByRole('button',{name:/2 sous-agents/})).toHaveAttribute('aria-expanded','false');
 await group.getByRole('button',{name:/2 sous-agents/}).focus();
 expect(await group.getByRole('button',{name:/2 sous-agents/}).evaluate(el=>getComputedStyle(el).outlineStyle)).toBe('none');
 await page.keyboard.press('Enter');
 await expect(page.getByRole('button',{name:'Ouvrir le sous-agent Feux 2015 2023'})).toBeVisible();
 await page.evaluate(()=>window.resume());
 await expect(group.getByRole('button',{name:/2 sous-agents/})).toHaveAttribute('aria-expanded','true');
 await page.setViewportSize({width:390,height:800});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.setViewportSize({width:1000,height:760});
 expect(await page.locator('.agent-row').evaluateAll(rows=>rows.every(row=>getComputedStyle(row).display==='flex'))).toBe(true);
 const workingColors=await page.locator('.agent-row[data-agent-status="working"]').evaluate(row=>({description:getComputedStyle(row.querySelector('.agent-row-description')).color,indicator:getComputedStyle(row.querySelector('.agent-state-icon')).color}));
 expect(workingColors.description).not.toBe(workingColors.indicator);
 expect(errors).toEqual([]);
 await group.getByRole('button',{name:/2 sous-agents/}).focus();
 expect(await group.getByRole('button',{name:/2 sous-agents/}).evaluate(el=>getComputedStyle(el).outlineStyle)).toBe('none');
 await page.screenshot({path:'/tmp/atelier-subagent-ui.png'});
});
